# Project 3


Amazon reviews analysis. 

This dataset consists of a few million Amazon customer reviews

 (input text) and star
ratings (output labels) for learning how to train fastText for sentiment analysis.

amazon dataset link: https://www.kaggle.com/datasets/bittlingmayer/amazonreviews

In [ ]:
!pip install torch #no change

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import torch #no change
from tqdm.notebook import tqdm #no changeimport numpy as np #no change
import pandas as pd #no change

In [ ]:
!pip install opendatasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#{"username":"jayrajsonawane","key":"da102502db5bf82fd43a87948b159128"}
import opendatasets as od
od.download(
    "https://www.kaggle.com/datasets/bittlingmayer/amazonreviews")

Skipping, found downloaded files in "./amazonreviews" (use force=True to force download)


In [ ]:
import pandas as pd
import bz2

# replace the file path with the path to the train data file in your downloaded dataset
train_file = '/content/amazonreviews/test.ft.txt.bz2'

# extract the train data from the compressed format and read it into a Pandas DataFrame
with bz2.open(train_file, 'rt') as f:
    train_data = f.readlines()
train_data = [x.strip() for x in train_data]
train_df = pd.DataFrame(train_data, columns=['text'])

# print the first 5 rows of the training DataFrame
print(train_df.head())


                                                text
0  __label__2 Great CD: My lovely Pat has one of ...
1  __label__2 One of the best game music soundtra...
2  __label__1 Batteries died within a year ...: I...
3  __label__2 works fine, but Maha Energy is bett...
4  __label__2 Great for the non-audiophile: Revie...


In [ ]:
train_df 

text
0       __label__2 Great CD: My lovely Pat has one of ...
1       __label__2 One of the best game music soundtra...
2       __label__1 Batteries died within a year ...: I...
3       __label__2 works fine, but Maha Energy is bett...
4       __label__2 Great for the non-audiophile: Revie...
...                                                   ...
399995  __label__1 Unbelievable- In a Bad Way: We boug...
399996  __label__1 Almost Great, Until it Broke...: My...
399997  __label__1 Disappointed !!!: I bought this toy...
399998  __label__2 Classic Jessica Mitford: This is a ...
399999  __label__1 Comedy Scene, and Not Heard: This D...

[400000 rows x 1 columns]

In [ ]:
import pandas as pd
import bz2

# replace the file path with the path to the test data file in your downloaded dataset
test_file = '/content/amazonreviews/train.ft.txt.bz2'

# extract the test data from the compressed format and read it into a Pandas DataFrame
with bz2.open(test_file, 'rt') as f:
    test_data = f.readlines()
test_data = [x.strip() for x in test_data]
test_df = pd.DataFrame(test_data, columns=['text'])

# print the first 5 rows of the test DataFrame
print(test_df.head())


                                                text
0  __label__2 Stuning even for the non-gamer: Thi...
1  __label__2 The best soundtrack ever to anythin...
2  __label__2 Amazing!: This soundtrack is my fav...
3  __label__2 Excellent Soundtrack: I truly like ...
4  __label__2 Remember, Pull Your Jaw Off The Flo...


In [ ]:
# convert train data to tabular form
train_df[['label', 'text']] = train_df['text'].str.split(' ', 1, expand=True)
train_df['label'] = train_df['label'].str.replace('__label__', '').astype(int)
train_df = train_df[['text', 'label']]

<ipython-input-8-108ab1e11f9e>:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  train_df[['label', 'text']] = train_df['text'].str.split(' ', 1, expand=True)


In [ ]:
# convert test data to tabular form
test_df[['label', 'text']] = test_df['text'].str.split(' ', 1, expand=True)
test_df['label'] = test_df['label'].str.replace('__label__', '').astype(int)
test_df = test_df[['text', 'label']]

<ipython-input-9-69bc363c0bf8>:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  test_df[['label', 'text']] = test_df['text'].str.split(' ', 1, expand=True)


In [ ]:
print(train_df.head())


                                                text  label
0  Great CD: My lovely Pat has one of the GREAT v...      2
1  One of the best game music soundtracks - for a...      2
2  Batteries died within a year ...: I bought thi...      1
3  works fine, but Maha Energy is better: Check o...      2
4  Great for the non-audiophile: Reviewed quite a...      2


In [ ]:
print(test_df.head())

                                                text  label
0  Stuning even for the non-gamer: This sound tra...      2
1  The best soundtrack ever to anything.: I'm rea...      2
2  Amazing!: This soundtrack is my favorite music...      2
3  Excellent Soundtrack: I truly like this soundt...      2
4  Remember, Pull Your Jaw Off The Floor After He...      2


In [ ]:
set(train_df.label)

{1, 2}

In [ ]:
set(test_df.label)

{1, 2}

In [ ]:
len(train_df)

400000

In [ ]:
len(test_df)

3600000

In [ ]:
print(train_df.iloc[0])


text     Great CD: My lovely Pat has one of the GREAT v...
label                                                    2
Name: 0, dtype: object


In [ ]:
# we will train only traning data cause data set is to big 

In [ ]:
df =train_df

In [ ]:
df

text  label
0       Great CD: My lovely Pat has one of the GREAT v...      2
1       One of the best game music soundtracks - for a...      2
2       Batteries died within a year ...: I bought thi...      1
3       works fine, but Maha Energy is better: Check o...      2
4       Great for the non-audiophile: Reviewed quite a...      2
...                                                   ...    ...
399995  Unbelievable- In a Bad Way: We bought this Tho...      1
399996  Almost Great, Until it Broke...: My son reciev...      1
399997  Disappointed !!!: I bought this toy for my son...      1
399998  Classic Jessica Mitford: This is a compilation...      2
399999  Comedy Scene, and Not Heard: This DVD will be ...      1

[400000 rows x 2 columns]

In [ ]:
df = df.sample(n=50000, random_state=42)

In [ ]:
df

text  label
23218   This is a great book: I must preface this by s...      2
20731   Huge Disappointment.: As a big time, long term...      1
39555   Wayne is tight but cant hang with Turk.: This ...      2
147506  Excellent: I read this book when I was in elem...      2
314215  Not about Anusara: Although this book is toute...      1
...                                                   ...    ...
311702  THE MIKADO: Clearly one of the best recordings...      2
165330  Barbie Goes to Hogwarts: My 9 y.o. son got thi...      1
32049   NOT THE OLD STANLEY - NEW CHINA MADE BOTTLE - ...      1
381911  Useful, inspiring, and stimulating.: As a "lay...      2
222760  how many times can you make the same album?: o...      1

[50000 rows x 2 columns]

In [ ]:

set(df.label)

{1, 2}

In [ ]:
df.label.value_counts()

1    25007
2    24993
Name: label, dtype: int64

In [ ]:
possible_labels = df.label.unique()

In [ ]:
possible_labels

array([2, 1])

In [ ]:
label_dict = {}
for index, possible_label in enumerate(possible_labels):
    label_dict[possible_label] = index

In [ ]:
label_dict

{2: 0, 1: 1}

In [ ]:

df.label= df['label'].map(label_dict)

In [ ]:
df.label.unique()

array([0, 1])

In [ ]:
df.head(10)

text  label
23218   This is a great book: I must preface this by s...      0
20731   Huge Disappointment.: As a big time, long term...      1
39555   Wayne is tight but cant hang with Turk.: This ...      0
147506  Excellent: I read this book when I was in elem...      0
314215  Not about Anusara: Although this book is toute...      1
190913  Worst DVD Ever purchased: This was the very wo...      1
296715  Not the strongest fan, but gets the job done.:...      0
141482  Bottom of the casebook barrel: At the beginnin...      1
49119   Hilarious!: This movie is very sweet, I love i...      0
208005  The swinging, sadly, occurs only in the title....      1

In [ ]:
import re

def clean_text(text):
    # Convert to lowercase
    text = text.lower()
    
    # Remove urls
    text = re.sub(r'http\S+', '', text)
    
    # Remove mentions
    text = re.sub(r'@\w+', '', text)
    
    # Remove hashtags
    text = re.sub(r'#\w+', '', text)
    
    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)
    
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

In [ ]:
df['text'] = df['text'].apply(clean_text)  # we clean all the text here 

In [ ]:
df

text  label
23218   this is a great book i must preface this by sa...      0
20731   huge disappointment as a big time long term tr...      1
39555   wayne is tight but cant hang with turk this al...      0
147506  excellent i read this book when i was in eleme...      0
314215  not about anusara although this book is touted...      1
...                                                   ...    ...
311702  the mikado clearly one of the best recordings ...      0
165330  barbie goes to hogwarts my yo son got this set...      1
32049   not the old stanley new china made bottle that...      1
381911  useful inspiring and stimulating as a layperso...      0
222760  how many times can you make the same album onl...      1

[50000 rows x 2 columns]

## 2: Training/Validation Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:

X_train, X_val, y_train, y_val = train_test_split(df.index.values, 
                                                   
                                                  df.label.values,
                                                  test_size=0.15, 
                                                  random_state=42,
                                                  stratify=df.label.values)

In [ ]:
len(df)

50000

In [ ]:
df['data_type'] = ['not_set']*df.shape[0]

In [ ]:
df.head()

text  label data_type
23218   this is a great book i must preface this by sa...      0   not_set
20731   huge disappointment as a big time long term tr...      1   not_set
39555   wayne is tight but cant hang with turk this al...      0   not_set
147506  excellent i read this book when i was in eleme...      0   not_set
314215  not about anusara although this book is touted...      1   not_set

In [ ]:
df.loc[X_train, 'data_type'] = 'train'
df.loc[X_val, 'data_type'] = 'val'

In [ ]:
df

text  label data_type
23218   this is a great book i must preface this by sa...      0     train
20731   huge disappointment as a big time long term tr...      1     train
39555   wayne is tight but cant hang with turk this al...      0     train
147506  excellent i read this book when i was in eleme...      0     train
314215  not about anusara although this book is touted...      1     train
...                                                   ...    ...       ...
311702  the mikado clearly one of the best recordings ...      0       val
165330  barbie goes to hogwarts my yo son got this set...      1     train
32049   not the old stanley new china made bottle that...      1     train
381911  useful inspiring and stimulating as a layperso...      0     train
222760  how many times can you make the same album onl...      1     train

[50000 rows x 3 columns]

In [ ]:

df.groupby(['label', 'data_type']).count()

text
label data_type       
0     train      21244
      val         3749
1     train      21256
      val         3751

###3. Loading Tokenizer and Encoding our Data

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from transformers import BertTokenizer
from torch.utils.data import TensorDataset

In [ ]:
tokenizer = BertTokenizer.from_pretrained(
    'bert-base-uncased', #bert-base-uncased using small bert model for simple data , bert-large-uncased fo large data
    do_lower_case=True
)

In [ ]:
encoded_data_train = tokenizer.batch_encode_plus(
    
     df[df.data_type=='train'].text.values,
    add_special_tokens=True,
    return_attention_mask=True,
    pad_to_max_length=True,
    max_length=256,
    return_tensors='pt'
)

encoded_data_val = tokenizer.batch_encode_plus(
    df[df.data_type=='val'].text.values,
    add_special_tokens=True,
    return_attention_mask=True,
    pad_to_max_length=True,
    max_length=256,
    return_tensors='pt'
)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2354: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


In [ ]:
input_ids_train = encoded_data_train['input_ids']
attention_masks_train = encoded_data_train['attention_mask']
labels_train = torch.tensor(df[df.data_type=='train'].label.values)

input_ids_val = encoded_data_val['input_ids']
attention_masks_val = encoded_data_val['attention_mask']
labels_val = torch.tensor(df[df.data_type=='val'].label.values)

In [ ]:
#TensorDataset create a single variable which stores info of inputids , attentionmsk, labels
dataset_train = TensorDataset(input_ids_train, 
                              attention_masks_train,
                              labels_train)

dataset_val = TensorDataset(input_ids_val, 
                            attention_masks_val,
                           labels_val)

In [ ]:
len(dataset_train)

42500

In [ ]:
len(dataset_val)

7500

In [ ]:
dataset_val.tensors

(tensor([[  101,  3953,  1997,  ...,     0,     0,     0],
         [  101,  2074,  2178,  ...,     0,     0,     0],
         [  101,  2052,  2022,  ...,     0,     0,     0],
         ...,
         [  101,  2919,  3185,  ...,     0,     0,     0],
         [  101,  1037,  2200,  ...,     0,     0,     0],
         [  101,  1996, 27857,  ...,     0,     0,     0]]),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 tensor([1, 1, 1,  ..., 1, 0, 0]))

In [ ]:
dataset_train.tensors

(tensor([[  101,  2023,  2003,  ...,     0,     0,     0],
         [  101,  4121, 10520,  ...,     0,     0,     0],
         [  101,  6159,  2003,  ...,     0,     0,     0],
         ...,
         [  101,  2025,  1996,  ...,     0,     0,     0],
         [  101,  6179, 18988,  ...,     0,     0,     0],
         [  101,  2129,  2116,  ...,     0,     0,     0]]),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 tensor([0, 1, 0,  ..., 1, 0, 1]))

### 4. Setting up BERT Pretrained Model¶

In [ ]:
from transformers import BertForSequenceClassification

In [ ]:
model = BertForSequenceClassification.from_pretrained(
                                      'bert-base-uncased', 
                                      num_labels = len(label_dict),#2
                                      output_attentions = False,
                                      output_hidden_states = False
                                     )

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

### 5. Creating Data Loaders

In [ ]:
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler

In [ ]:
batch_size = 50

dataloader_train = DataLoader(
    dataset_train,
    sampler=RandomSampler(dataset_train),
    batch_size=batch_size
)

dataloader_val = DataLoader(
    dataset_val,
    sampler=RandomSampler(dataset_val),
    batch_size=32
)

### 6. Setting Up Optimizer and Scheduler¶

In [ ]:
from transformers import AdamW, get_linear_schedule_with_warmup

In [ ]:
optimizer = AdamW(
    model.parameters(),
    lr = 1e-5,
    eps = 1e-8
)

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [ ]:
epochs = 1

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=0,
    num_training_steps = len(dataloader_train)*epochs
)

### 7. Defining our Performance Metrics

In [ ]:
import numpy as np
from sklearn.metrics import f1_score

In [ ]:
def f1_score_func(preds, labels):
    preds_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return f1_score(labels_flat, preds_flat, average = 'weighted')

In [ ]:
def accuracy_per_class(preds, labels):
    label_dict_inverse = {v: k for k, v in label_dict.items()}
    
    preds_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    
    for label in np.unique(labels_flat):
        y_preds = preds_flat[labels_flat==label]
        y_true = labels_flat[labels_flat==label]
        print(f'Class: {label_dict_inverse[label]}')
        print(f'Accuracy:{len(y_preds[y_preds==label])}/{len(y_true)}\n')

### 8. Creating our Training Loop

In [ ]:
import random

seed_val = 17
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
print(device)

cuda


In [ ]:
def evaluate(dataloader_val):

    model.eval()
    
    loss_val_total = 0
    predictions, true_vals = [], []
    
    for batch in tqdm(dataloader_val):
        
        batch = tuple(b.to(device) for b in batch)
        
        inputs = {'input_ids':      batch[0],
                  'attention_mask': batch[1],
                  'labels':         batch[2],
                 }

        with torch.no_grad():        
            outputs = model(**inputs)
            
        loss = outputs[0]
        logits = outputs[1]
        loss_val_total += loss.item()

        logits = logits.detach().cpu().numpy()
        label_ids = inputs['labels'].cpu().numpy()
        predictions.append(logits)
        true_vals.append(label_ids)
    
    loss_val_avg = loss_val_total/len(dataloader_val) 
    
    predictions = np.concatenate(predictions, axis=0)
    true_vals = np.concatenate(true_vals, axis=0)
            
    return loss_val_avg, predictions, true_vals

In [ ]:
for epoch in tqdm(range(1, epochs+1)):
    model.train() #forward propagation
    loss_train_total = 0
    
    progress_bar = tqdm(dataloader_train, 
                        desc='Epoch {:1d}'.format(epoch), 
                        leave=False, 
                        disable=False)
    
    for batch in progress_bar:
        model.zero_grad()
        batch = tuple(b.to(device) for b in batch)
        inputs = {
            'input_ids': batch[0],
            'attention_mask': batch[1],
            'labels': batch[2]
        }
        
        outputs = model(**inputs)
        loss = outputs[0]
        loss_train_total +=loss.item()
        loss.backward() #backwardprop
        
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        
        optimizer.step()
        scheduler.step()
        
        progress_bar.set_postfix({'training_loss': '{:.3f}'.format(loss.item()/len(batch))})     
    
    torch.save(model, f'BERT_ft_Epoch_amazon{epoch}.model')
    
    tqdm.write(f'\nEpoch {epoch}')
    
    loss_train_avg = loss_train_total/len(dataloader_train)
    tqdm.write(f'Training loss: {loss_train_avg}')
    
    val_loss, predictions, true_vals = evaluate(dataloader_val)
    val_f1 = f1_score_func(predictions, true_vals)
    tqdm.write(f'Validation loss: {val_loss}')
    tqdm.write(f'F1 Score (weighted): {val_f1}')

  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1:   0%|          | 0/850 [00:00<?, ?it/s]


Epoch 1
Training loss: 0.21212715645485064


  0%|          | 0/235 [00:00<?, ?it/s]

Validation loss: 0.1625880955104181
F1 Score (weighted): 0.9394657626877586


## EVALUATION

In [ ]:
import torch

In [ ]:

headline = ''' Not satisfied with the product: I bought this product expecting it to be of good quality,
 but I was disappointed with its performance. It broke down within a few days of use and I had to
  return it. Would not recommend.'''


In [ ]:
from transformers import BertTokenizer

In [ ]:
tokenizer = BertTokenizer.from_pretrained(
    'bert-base-uncased', #bert-base-uncased using small bert model for simple data , bert-large-uncased fo large data
    do_lower_case=True
)

In [ ]:
device = torch.device('cpu')

In [ ]:
print(device)

cpu


In [ ]:
encoded_headline = tokenizer(headline, return_tensors = 'pt')

In [ ]:
encoded_headline

{'input_ids': tensor([[  101,  2025,  8510,  2007,  1996,  4031,  1024,  1045,  4149,  2023,
          4031,  8074,  2009,  2000,  2022,  1997,  2204,  3737,  1010,  2021,
          1045,  2001,  9364,  2007,  2049,  2836,  1012,  2009,  3631,  2091,
          2306,  1037,  2261,  2420,  1997,  2224,  1998,  1045,  2018,  2000,
          2709,  2009,  1012,  2052,  2025, 16755,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
input_ids = encoded_headline['input_ids'].to(device)
attention_msk = encoded_headline['attention_mask'].to(device)

In [ ]:
path = '/content/BERT_ft_Epoch_amazon1.model'
model = torch.load(path, map_location = torch.device('cpu'))

In [ ]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12,

In [ ]:
model_output = model(input_ids,attention_msk)

In [ ]:
model_output

SequenceClassifierOutput(loss=None, logits=tensor([[-1.7898,  2.1231]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
model_output_tensor = torch.tensor(model_output.logits)

<ipython-input-80-d2b33ccd89fe>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  model_output_tensor = torch.tensor(model_output.logits)


In [ ]:
model_output_tensor_categoryIndex = int(torch.argmax(model_output_tensor))

In [ ]:
model_output_tensor_categoryIndex

1

In [ ]:
classes = {0: 'positive sentiment', 1: 'negative sentiment'}


In [ ]:
classes[model_output_tensor_categoryIndex]

'negative sentiment'